# frozen_string_literal: true

# This file was generated by RubyRoad 0.3.0 from an OpenAPI specification.
# Regenerating will overwrite local changes.
#
# Space Payments provider service generated from OpenAPI.
# Drop this file into the host app at app/services/provider/novapay_service.rb
# (use --out app/services/provider). Subclasses the host Provider::BaseService.

require "faraday"
require "json"
require "openssl"
require "base64"

begin
  require "provider/base_service"
rescue LoadError
  # Host apps load Provider::BaseService themselves. Fallback is only for
  # RubyRoad's in-repo stub when loading generated files under ./output.
  require_relative "../lib/provider/base_service"
end

require "uri"

class Provider::NovapayService < Provider::BaseService
  BASE_URL = ENV.fetch("NOVAPAY_BASE_URL", "https://api.sandbox.novapay.example/v1")
  LIVE_URL = "https://api.novapay.example/v1"
  AUTH_HEADER = "X-API-Key"
  IDEMPOTENCY_HEADER = "Idempotency-Key"
  SIGNATURE_HEADER = "X-NovaPay-Signature"
  SIGNATURE_ENCODING = "hex"
  AMOUNT_SCALE = 100
  MIN_AMOUNT_MAJOR = 1000

  STATUS_MAP = {
    "pending" => "in_progress",
    "processing" => "in_progress",
    "completed" => "approved",
    "failed" => "rejected",
    "cancelled" => "rejected",
  }.freeze

  ERROR_MAP = {
    400 => :invalid_request,
    401 => :unauthorized,
    402 => :insufficient_balance,
    404 => :not_found,
    409 => :conflict,
    422 => :validation_error,
    429 => :rate_limited,
    500 => :provider_error
  }.freeze

  PAYOUT_METHODS = ["sbp", "card"].freeze
  CREATE_ACTIONS = %w[create check payout].freeze

  def check_conditions(operation, request_method)
    result = super
    return result if result.is_a?(Hash) && result[:success] == false

    if create_action?(request_method)
      amount = operation_amount(operation)
      if amount && amount < MIN_AMOUNT_MAJOR
        return failure(:amount_too_low, "Amount must be at least #{MIN_AMOUNT_MAJOR} RUB (spec minimum is 100000 minor units)")
      end
    end
    if create_action?(request_method)
      phone = requisite_value(operation, "phone")
      if phone && !phone.to_s.match?(Regexp.new("^7\\d{10}$"))
        return failure(:invalid_phone, "Recipient phone must match #{Regexp.new("^7\\d{10}$").source}")
      end
    end
    if create_action?(request_method)
      expected = "sbp"
      type = request_method.to_s.downcase == expected ? expected : requisite_value(operation, "type").to_s
      if type == expected && requisite_value(operation, "bank_code").to_s.empty?
        return failure(:missing_bank_code, "bank_code is required when type=sbp")
      end
    end
    if create_action?(request_method)
      expected = "card"
      type = request_method.to_s.downcase == expected ? expected : requisite_value(operation, "type").to_s
      if type == expected && requisite_value(operation, "card_number").to_s.empty?
        return failure(:missing_card_number, "card_number is required when type=card")
      end
    end

    success
  end

  # POST /payouts (createPayout)
  def create_request(operation, request_method = :create)
    precheck = check_conditions(operation, request_method)
    return precheck unless precheck[:success]

    headers = auth_headers
    key = operation_value(operation, :idempotency_key)
    headers[IDEMPOTENCY_HEADER] = key if key

    response = client.post(full_path("/payouts")) do |req|
      req.headers.update(headers)
      req.body = build_payout_payload(operation)
    end
    payload = parse_json(response.body)
    raise Provider::UnauthorizedError, error_message(payload, response) if response.status == 401
    raise Provider::RateLimitError, error_message(payload, response) if response.status == 429

    unless response.success?
      return mapped_error(response, payload)
    end

    provider_id = payload["id"] || payload["payout_id"]
    success(
      provider_operation_id: provider_id,
      provider_status: payload["status"],
      mapped_status: map_status(payload["status"]),
      payload: payload
    )
  rescue Provider::RateLimitError => e
    failure(:rate_limited, e.message)
  rescue Provider::UnauthorizedError => e
    failure(:unauthorized, e.message)
  rescue Faraday::UnauthorizedError => e
    failure(:unauthorized, e.message)
  rescue Faraday::ConnectionFailed, Faraday::TimeoutError => e
    failure(:connection_error, e.message)
  end

  # GET /payouts/{payout_id} (getPayoutStatus)
  def fetch_status(operation)
    precheck = check_conditions(operation, :status)
    return precheck unless precheck[:success]

    provider_id = operation_value(operation, :provider_operation_id)
    return failure(:missing_provider_id, "operation.provider_operation_id is required") if provider_id.to_s.empty?

    path = full_path(expand_path("/payouts/{payout_id}", provider_id))
    response = client.get(path) do |req|
      req.headers.update(auth_headers)
    end
    payload = parse_json(response.body)
    raise Provider::UnauthorizedError, error_message(payload, response) if response.status == 401
    raise Provider::RateLimitError, error_message(payload, response) if response.status == 429
    return mapped_error(response, payload) unless response.success?

    mapped = map_status(payload["status"])
    apply_mapped_status(operation, mapped, payload)
    success(provider_status: payload["status"], mapped_status: mapped, payload: payload)
  rescue Provider::RateLimitError => e
    failure(:rate_limited, e.message)
  rescue Provider::UnauthorizedError => e
    failure(:unauthorized, e.message)
  end

  # POST /webhooks/payout (payoutWebhook)
  def process_callback(payload)
    raw, headers = normalize_callback(payload)
    verify_signature!(raw, headers)
    data = parse_json(raw)
    event = data["event"] || data["type"]
    status = data["status"]
    mapped = map_status(status)
    operation_ref = data["external_id"] || data["payout_id"] || data["id"]

    case event.to_s
    when /complet|success|approved/
      approve_operation(operation_ref, provider_status: status, event: event, payload: data)
    when /fail|reject|cancel|declin/
      reject_operation(operation_ref, provider_status: status, event: event, payload: data)
    else
      logger&.info("webhook event #{event} mapped to #{mapped}")
    end

    success(event: event, mapped_status: mapped, received: true)
  rescue Provider::SignatureError => e
    failure(:invalid_signature, e.message)
  end

  # POST /payouts/{payout_id}/cancel (cancelPayout)
  def cancel_request(operation)
    precheck = check_conditions(operation, :cancel)
    return precheck unless precheck[:success]

    provider_id = operation_value(operation, :provider_operation_id)
    return failure(:missing_provider_id, "operation.provider_operation_id is required") if provider_id.to_s.empty?

    path = full_path(expand_path("/payouts/{payout_id}/cancel", provider_id))
    response = client.post(path) do |req|
      req.headers.update(auth_headers)
    end
    payload = parse_json(response.body)
    return mapped_error(response, payload) unless response.success?

    success(provider_status: payload["status"], mapped_status: map_status(payload["status"]), payload: payload)
  end

  # GET /balance (getBalance)
  def get_balance
    response = client.get(full_path("/balance")) do |req|
      req.headers.update(auth_headers)
    end
    payload = parse_json(response.body)
    return mapped_error(response, payload) unless response.success?

    success(payload: payload)
  end

  def client
    origin, @path_prefix = split_base(BASE_URL)
    @client ||= Faraday.new(url: origin) do |faraday|
      faraday.request :json
      faraday.response :json, content_type: /\bjson$/
      faraday.adapter Faraday.default_adapter
    end
  end

  def auth_headers
    { AUTH_HEADER => api_key, "Content-Type" => "application/json", "Accept" => "application/json" }
  end

  def map_status(provider_status)
    STATUS_MAP.fetch(provider_status.to_s) { "in_progress" }
  end

  private

  def api_key
    ENV.fetch("NOVAPAY_API_KEY") do
      credentials["api_key"] || credentials["token"] || raise(Provider::UnauthorizedError, "NOVAPAY_API_KEY is missing")
    end
  end

  def callback_secret
    ENV.fetch("NOVAPAY_CALLBACK_SECRET") do
      credentials["callback_secret"] || credentials["webhook_secret"] || ""
    end
  end

  def build_payout_payload(operation)
    req = hashify(operation_value(operation, :payout_requisite) || operation_value(operation, :requisite) || {})
    amount_major = operation_amount(operation)
    {
      amount: (amount_major.to_r * AMOUNT_SCALE).to_i,
      currency: (operation_value(operation, :currency) || "RUB").to_s,
      external_id: operation_value(operation, :id).to_s,
      recipient: {
        type: req["type"] || req[:type],
        phone: req["phone"] || req[:phone],
        bank_code: req["bank_code"] || req[:bank_code],
        bank_name: req["bank_name"] || req[:bank_name],
        card_number: req["card_number"] || req[:card_number],
      }.compact,
    }.compact
  end

  def verify_signature!(raw_body, headers)
    secret = callback_secret
    raise Provider::SignatureError, "callback secret is missing" if secret.to_s.empty?

    provided = header_value(headers, SIGNATURE_HEADER)
    raise Provider::SignatureError, "missing #{SIGNATURE_HEADER} header" if provided.to_s.empty?

    expected = OpenSSL::HMAC.hexdigest("SHA256", secret, raw_body.to_s)
    provided_hex = provided.to_s.sub(/\Asha256=/i, "")
    unless secure_compare(expected, provided_hex)
      raise Provider::SignatureError, "invalid #{SIGNATURE_HEADER}"
    end
    true
  end

  def normalize_callback(payload)
    case payload
    when String
      [payload, {}]
    when Hash
      if payload[:body] || payload["body"]
        raw = payload[:body] || payload["body"]
        headers = payload[:headers] || payload["headers"] || {}
        raw = JSON.generate(raw) unless raw.is_a?(String)
        [raw, headers]
      else
        [JSON.generate(payload), payload[:headers] || payload["headers"] || {}]
      end
    else
      if payload.respond_to?(:body) && payload.respond_to?(:headers)
        body = payload.body
        body = body.read if body.respond_to?(:read)
        [body.to_s, payload.headers]
      else
        [payload.to_s, {}]
      end
    end
  end

  def expand_path(template, provider_id)
    template.gsub(/\{[^}]+\}/) { URI.encode_www_form_component(provider_id.to_s) }
  end

  def full_path(path)
    origin, prefix = split_base(BASE_URL)
    _ = origin
    "#{prefix}#{path.start_with?('/') ? path : "/#{path}"}"
  end

  def split_base(url)
    uri = URI.parse(url)
    origin = "#{uri.scheme}://#{uri.host}"
    origin += ":#{uri.port}" if uri.port && ![80, 443].include?(uri.port)
    prefix = uri.path.to_s.sub(%r{/\z}, "")
    [origin, prefix]
  end

  def parse_json(body)
    return body if body.is_a?(Hash)
    return {} if body.nil? || body.to_s.empty?

    JSON.parse(body)
  rescue JSON::ParserError
    { "raw" => body.to_s }
  end

  def mapped_error(response, payload)
    code = ERROR_MAP[response.status] || :provider_error
    failure(code, error_message(payload, response), http_status: response.status, payload: payload)
  end

  def error_message(payload, response)
    err = payload.is_a?(Hash) ? (payload["error"] || payload) : {}
    err = {} unless err.is_a?(Hash)
    err["message"] || err[:message] || "HTTP #{response.status}"
  end

  def apply_mapped_status(operation, mapped, payload)
    case mapped
    when "approved"
      approve_operation(operation, payload: payload)
    when "rejected"
      reject_operation(operation, payload: payload)
    end
  end

  def create_action?(request_method)
    token = request_method.to_s.downcase
    return false if %w[status fetch cancel].include?(token)
    return true if %w[create check payout].include?(token)
    return true if PAYOUT_METHODS.include?(token)

    false
  end

  def operation_amount(operation)
    value = operation_value(operation, :amount)
    return if value.nil?
    raise ArgumentError, "amount must be integer major units, never Float" if value.is_a?(Float)

    value.to_r
  end

  def operation_value(operation, key)
    return if operation.nil?

    if operation.respond_to?(key)
      operation.public_send(key)
    elsif operation.is_a?(Hash)
      operation[key] || operation[key.to_s]
    end
  end

  def requisite_value(operation, key)
    req = hashify(operation_value(operation, :payout_requisite) || operation_value(operation, :requisite) || {})
    req[key] || req[key.to_sym]
  end

  def hashify(value)
    return {} if value.nil?
    return value.transform_keys(&:to_s) if value.is_a?(Hash)
    return value.to_h.transform_keys(&:to_s) if value.respond_to?(:to_h)

    {}
  end

  def header_value(headers, name)
    return if headers.nil?

    headers[name] || headers[name.downcase] || headers[name.upcase] ||
      headers["HTTP_#{name.upcase.tr('-', '_')}"]
  end

  def secure_compare(left, right)
    return false if left.nil? || right.nil? || left.bytesize != right.bytesize

    OpenSSL.fixed_length_secure_compare(left, right)
  end
end
